name: Release

on:
  push:
    tags:
      - "*"

jobs:
  build_win:
    name: "Build for Linux"
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          cache: "pip"
      - run: "pip install -r requirements.txt"

      - name: "Create EXE"
        run: "python3 ./install.py"
      - run: "cp ./messages.json ./dist/messages.json"
      - run: "mv ./dist/main.exe ./dist/elite-macro-overlay.exe"
      - name: "Upload Artifact"
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: "./dist"

  publish:
    needs:
      - build_win
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@master
        with:
          name: output
          path: "./out"
      - name: ZIP
        run: |
          cd out
          zip -r elite-macro-overlay.zip .
          cd ..
          mv ./out/elite-macro-overlay.zip .
      - uses: ncipollo/release-action@v1
        with:
          artifacts: elite-macro-overlay.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true